nginx:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - .:/var/www
        - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
        - php

php:
    build: .
    dockerfile: docker/php/dockerfile
    volumes:
        - .:/var/www